In [1]:
%matplotlib inline

In [48]:
import numpy as np
import pandas as pd
import matplotlib_inline as plt

from sklearn.datasets import load_iris, make_circles

from sklearn.preprocessing import PolynomialFeatures

from sklearn.model_selection import train_test_split

# from sklearn.linear_model import LogisticRegression
from sklearn.svm import LinearSVC, LinearSVR, SVC, OneClassSVM
from sklearn.neighbors import KNeighborsClassifier

# Support Vector Machines

## Misc notes

Look up:  


Late fusion - https://medium.com/@raj.pulapakura/multimodal-models-and-fusion-a-complete-guide-225ca91f6861

Early fusion

Gradient boosting vs. Adaptive boosting

Label propagation

Data drift

Observed minus estimated

Data partitioning / Data shattering

Convex hull

Squared hinge loss function

Elastic Net Regression - combines the features of both Lasso (L1) and Ridge (L2) Regression  

https://medium.com/@shruti.dhumne/elastic-net-regression-detailed-guide-99dce30b8e6e

OVR - One vs. rest  

Crammer-Singer method for LinearSVM - https://github.com/scikit-learn/scikit-learn/issues/13556  
- similar to Softmax in Logistic Regression - https://medium.com/@tpreethi/softmax-regression-93808c02e6ac

### **SVR explained:**  

SVR tries to find a function that fits the data points as closely as possible, but within a certain tolerance. The SVR approach introduces a margin of tolerance 
$\epsilon$ around the regression line. The idea is to ignore errors that are smaller than 
$\epsilon$ and only penalize errors that are larger than this margin.

#### Logic of Linear SVR:
- **Goal:** Fit a linear function 
$f(x) = w^T x + b$ to the data while allowing some flexibility (errors) within the margin $\epsilon$.
- **Support Vectors:** In SVR, the support vectors are the data points that fall outside the $\epsilon$-margin of the regression line. These points are used to determine the final regression line.
- **Loss Function:** SVR uses a special type of loss function called **epsilon-insensitive loss**. This loss function doesn't penalize errors as long as they are within the margin $\epsilon$. For errors outside the margin, the penalty grows linearly with the error size.
- **Regression:** The final model attempts to minimize the error while keeping most of the data within the $\epsilon$-margin. The choice of $\epsilon$ controls how sensitive the model is to small errors.

In short, SVR fits the best possible line (or hyperplane) that keeps most of the data within the $\epsilon$-distance from the line, treating errors within that margin as acceptable and only focusing on larger deviations. The support vectors in SVR are the data points outside this margin that influence the regression line.


**Cover's theorem** - https://en.wikipedia.org/wiki/Cover%27s_theorem  

Cover's theorem states that a complex, non-linearly separable problem in a low-dimensional space is more likely to become linearly separable when mapped to a higher-dimensional space using a nonlinear transformation.

Radial Basis Function kernel 

Instance based learning

Voronoi tessellation

Anomaly detection - https://medium.com/@venujkvenk/anomaly-detection-techniques-a-comprehensive-guide-with-supervised-and-unsupervised-learning-67671cdc9680

Novely detection (and outliers) - https://scikit-learn.org/1.5/modules/outlier_detection.html

## Demo

In [4]:
iris_dataset = load_iris()

In [5]:
attributes, targets = iris_dataset["data"], iris_dataset["target"]

In [25]:
poly_attributes = PolynomialFeatures(degree = 3).fit_transform(attributes)

In [19]:
simple_svm = LinearSVC(C = 1e-3)

In [20]:
simple_svm.fit(attributes, targets)

LinearSVC(C=0.001)

In [21]:
simple_svm.coef_

array([[ 0.01439037,  0.10003511, -0.1860645 , -0.08267264],
       [-0.03772127, -0.07470283,  0.03918079,  0.00299687],
       [-0.07744765, -0.09388869,  0.11991649,  0.07658286]])

In [22]:
simple_svm.predict(attributes)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [23]:
simple_svm.score(attributes, targets)

0.6666666666666666

In [26]:
poly_svm = LinearSVC(C = 1e-3)

In [27]:
poly_svm.fit(poly_attributes, targets)

/opt/anaconda3/lib/python3.11/site-packages/sklearn/svm/_base.py:1244: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(


LinearSVC(C=0.001)

In [28]:
poly_svm.score(poly_attributes, targets)

0.98

In [33]:
circles_attributes, circles_targets = make_circles(noise = 0.1, factor = 0.5)

In [32]:
circles_svm_with_kernel = SVC(kernel = "poly", degree = 2)

In [35]:
circles_svm_with_kernel.fit(circles_attributes, circles_targets)

SVC(degree=2, kernel='poly')

In [36]:
circles_svm_with_kernel.score(circles_attributes, circles_targets)

0.98

In [40]:
pulsars = pd.read_csv("data/pulsar_stars.csv")

In [41]:
pulsars

Mean of the integrated profile  \
0                           140.562500   
1                           102.507812   
2                           103.015625   
3                           136.750000   
4                            88.726562   
...                                ...   
17893                       136.429688   
17894                       122.554688   
17895                       119.335938   
17896                       114.507812   
17897                        57.062500   

        Standard deviation of the integrated profile  \
0                                          55.683782   
1                                          58.882430   
2                                          39.341649   
3                                          57.178449   
4                                          40.672225   
...                                              ...   
17893                                      59.847421   
17894                                      49.485605   
17895                                      59.935939   
17896                                      53.902400   
17897                                      85.797340   

        Excess kurtosis of the integrated profile  \
0                                       -0.234571   
1                                        0.465318   
2                                        0.323328   
3                                       -0.068415   
4                                        0.600866   
...                                           ...   
17893                                   -0.187846   
17894                                    0.127978   
17895                                    0.159363   
17896                                    0.201161   
17897                                    1.406391   

        Skewness of the integrated profile   Mean of the DM-SNR curve  \
0                                -0.699648                   3.199833   
1                                -0.515088                   1.677258   
2                                 1.051164                   3.121237   
3                                -0.636238                   3.642977   
4                                 1.123492                   1.178930   
...                                    ...                        ...   
17893                            -0.738123                   1.296823   
17894                             0.323061                  16.409699   
17895                            -0.743025                  21.430602   
17896                            -0.024789                   1.946488   
17897                             0.089520                 188.306020   

        Standard deviation of the DM-SNR curve  \
0                                    19.110426   
1                                    14.860146   
2                                    21.744669   
3                                    20.959280   
4                                    11.468720   
...                                        ...   
17893                                12.166062   
17894                                44.626893   
17895                                58.872000   
17896                                13.381731   
17897                                64.712562   

        Excess kurtosis of the DM-SNR curve   Skewness of the DM-SNR curve  \
0                                  7.975532                      74.242225   
1                                 10.576487                     127.393580   
2                                  7.735822                      63.171909   
3                                  6.896499                      53.593661   
4                                 14.269573                     252.567306   
...                                     ...                            ...   
17893                             15.450260                     285.931022   
17894                              2.945244                       8.297092   
17895        

In [42]:
pulsars.target_class.value_counts(normalize = True)

target_class
0    0.908426
1    0.091574
Name: proportion, dtype: float64

In [43]:
pulsar_attributes_train, pulsar_attributes_test, pulsar_targets_train, pulsar_targets_test = train_test_split(
    pulsars.drop(columns = "target_class"),
    pulsars.target_class,
    test_size = 0.25,
    stratify = pulsars.target_class
)

In [44]:
svm = SVC(kernel = "rbf", gamma = 2)

In [45]:
svm.fit(pulsar_attributes_train, pulsar_targets_train)

SVC(gamma=2)

In [46]:
svm.score(pulsar_attributes_train, pulsar_targets_train)

0.9999255010057364

In [47]:
svm.score(pulsar_attributes_test, pulsar_targets_test)

0.9083798882681564

In [49]:
detector = OneClassSVM()

In [50]:
detector.fit(pulsar_attributes_train)

OneClassSVM()

In [51]:
detector.predict(pulsar_attributes_train)

array([ 1, -1,  1, ..., -1, -1,  1])